bsub -qs root "./macro/trigger/Matrix_Pattern_Checker.C(6,0,2,1)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_Checker.C(6,0,2,2)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_Checker.C(6,0,2,4)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_Checker.C(6,0,2,5)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_Checker.C(6,0,2,6)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_Checker.C(6,0,2,8)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_Checker.C(6,0,2,10)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_Checker.C(6,0,2,15)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_Checker.C(6,0,2,20)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_Checker.C(6,0,2,50)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_Checker.C(6,0,2,100)" -b
