bsub -qs root "./macro/trigger/Matrix_Pattern_NewMaker.C(6,0,2,1)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_NewMaker.C(6,0,2,5)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_NewMaker.C(6,0,2,10)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_NewMaker.C(6,0,2,20)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_NewMaker.C(6,0,2,25)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_NewMaker.C(6,0,2,30)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_NewMaker.C(6,0,2,36)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_NewMaker.C(6,0,2,40)" -b
bsub -qs root "./macro/trigger/Matrix_Pattern_NewMaker.C(6,0,2,50)" -b
