{
//////////////////////////////////////////////////////////
//   This file has been automatically generated 
//     (Tue Jan 15 16:04:27 2019 by ROOT version6.10/08)
//   from TTree pik/tree of PiKAna
//   found on file: analyzer_jun/rootfile/run05368_DstPiKAna.root
//////////////////////////////////////////////////////////


//Reset ROOT and connect tree file
   gROOT->Reset();
   TFile *f = (TFile*)gROOT->GetListOfFiles()->FindObject("analyzer_jun/rootfile/run05368_DstPiKAna.root");
   if (!f) {
      f = new TFile("analyzer_jun/rootfile/run05368_DstPiKAna.root");
   }
    f->GetObject("pik",tree);

//Declaration of leaves types
   Int_t           runnum;
   Int_t           evnum;
   Int_t           spill;
   Int_t           trigpat[32];
   Int_t           trigflag[32];
   Int_t           nhBh1;
   Int_t           csBh1[6];
   Double_t        Bh1Seg[6];
   Double_t        tBh1[6];
   Double_t        dtBh1[6];
   Double_t        deBh1[6];
   Double_t        btof[6];
   Int_t           nhBh2;
   Int_t           csBh2[5];
   Double_t        Bh2Seg[5];
   Double_t        tBh2[5];
   Double_t        t0Bh2[5];
   Double_t        dtBh2[5];
   Double_t        deBh2[5];
   Int_t           nhTof;
   Int_t           csTof[22];
   Double_t        TofSeg[22];
   Double_t        tTof[22];
   Double_t        dtTof[22];
   Double_t        deTof[22];
   Int_t           nhBft;
   Int_t           csBft[33];
   Double_t        tBft[33];
   Double_t        wBft[33];
   Double_t        BftPos[33];
   Int_t           nhSch;
   Int_t           csSch[27];
   Double_t        tSch[27];
   Double_t        wSch[27];
   Double_t        SchPos[27];
   Double_t        SchSeg[27];
   Double_t        delta_x[27];
   Double_t        delta_seg[27];
   Int_t           nhSftX;
   Double_t        SftXSeg[69];
   Int_t           nlBcOut;
   Int_t           ntBcOut;
   Int_t           nhBcOut[4];
   Double_t        chisqrBcOut[4];
   Double_t        x0BcOut[4];
   Double_t        y0BcOut[4];
   Double_t        u0BcOut[4];
   Double_t        v0BcOut[4];
   Double_t        xtgtBcOut[4];
   Double_t        ytgtBcOut[4];
   Double_t        xbh2BcOut[4];
   Double_t        ybh2BcOut[4];
   Int_t           ntK18;
   Int_t           nhK18[4];
   Double_t        chisqrK18[4];
   Double_t        pK18[4];
   Double_t        xtgtK18[4];
   Double_t        ytgtK18[4];
   Double_t        utgtK18[4];
   Double_t        vtgtK18[4];
   Double_t        thetaK18[4];
   Int_t           nlSdcIn;
   Int_t           ntSdcIn;
   Int_t           nhSdcIn[8];
   Double_t        chisqrSdcIn[8];
   Double_t        x0SdcIn[8];
   Double_t        y0SdcIn[8];
   Double_t        u0SdcIn[8];
   Double_t        v0SdcIn[8];
   Int_t           nlSdcOut;
   Int_t           ntSdcOut;
   Int_t           nhSdcOut[4];
   Double_t        chisqrSdcOut[4];
   Double_t        x0SdcOut[4];
   Double_t        y0SdcOut[4];
   Double_t        u0SdcOut[4];
   Double_t        v0SdcOut[4];
   Int_t           ntKurama;
   Int_t           nhKurama[4];
   Double_t        chisqrKurama[4];
   Double_t        stof[4];
   Double_t        path[4];
   Double_t        pKurama[4];
   Double_t        qKurama[4];
   Double_t        m2[4];
   Double_t        xtgtKurama[4];
   Double_t        ytgtKurama[4];
   Double_t        utgtKurama[4];
   Double_t        vtgtKurama[4];
   Double_t        thetaKurama[4];
   Double_t        xtofKurama[4];
   Double_t        ytofKurama[4];
   Double_t        utofKurama[4];
   Double_t        vtofKurama[4];
   Double_t        tofsegKurama[4];
   Double_t        sftxsegKurama;
   Double_t        vpx[5];
   Double_t        vpy[5];
   Double_t        vpseg[5];
   Int_t           nPi;
   Int_t           nK;
   Int_t           nPiK;
   Double_t        vtx[12];
   Double_t        vty[12];
   Double_t        vtz[12];
   Double_t        closeDist[12];
   Double_t        theta[12];
   Double_t        MissMass[12];
   Double_t        MissMassCorr[12];
   Double_t        MissMassCorrDE[12];
   Double_t        thetaCM[12];
   Double_t        costCM[12];
   Double_t        xpi[12];
   Double_t        ypi[12];
   Double_t        upi[12];
   Double_t        vpi[12];
   Double_t        xk[12];
   Double_t        yk[12];
   Double_t        uk[12];
   Double_t        vk[12];
   Double_t        pOrg[12];
   Double_t        pCalc[12];
   Double_t        pCorr[12];
   Double_t        pCorrDE[12];

   // Set branch addresses.
   pik->SetBranchAddress("runnum",&runnum);
   pik->SetBranchAddress("evnum",&evnum);
   pik->SetBranchAddress("spill",&spill);
   pik->SetBranchAddress("trigpat",trigpat);
   pik->SetBranchAddress("trigflag",trigflag);
   pik->SetBranchAddress("nhBh1",&nhBh1);
   pik->SetBranchAddress("csBh1",csBh1);
   pik->SetBranchAddress("Bh1Seg",Bh1Seg);
   pik->SetBranchAddress("tBh1",tBh1);
   pik->SetBranchAddress("dtBh1",dtBh1);
   pik->SetBranchAddress("deBh1",deBh1);
   pik->SetBranchAddress("btof",btof);
   pik->SetBranchAddress("nhBh2",&nhBh2);
   pik->SetBranchAddress("csBh2",csBh2);
   pik->SetBranchAddress("Bh2Seg",Bh2Seg);
   pik->SetBranchAddress("tBh2",tBh2);
   pik->SetBranchAddress("t0Bh2",t0Bh2);
   pik->SetBranchAddress("dtBh2",dtBh2);
   pik->SetBranchAddress("deBh2",deBh2);
   pik->SetBranchAddress("nhTof",&nhTof);
   pik->SetBranchAddress("csTof",csTof);
   pik->SetBranchAddress("TofSeg",TofSeg);
   pik->SetBranchAddress("tTof",tTof);
   pik->SetBranchAddress("dtTof",dtTof);
   pik->SetBranchAddress("deTof",deTof);
   pik->SetBranchAddress("nhBft",&nhBft);
   pik->SetBranchAddress("csBft",csBft);
   pik->SetBranchAddress("tBft",tBft);
   pik->SetBranchAddress("wBft",wBft);
   pik->SetBranchAddress("BftPos",BftPos);
   pik->SetBranchAddress("nhSch",&nhSch);
   pik->SetBranchAddress("csSch",csSch);
   pik->SetBranchAddress("tSch",tSch);
   pik->SetBranchAddress("wSch",wSch);
   pik->SetBranchAddress("SchPos",SchPos);
   pik->SetBranchAddress("SchSeg",SchSeg);
   pik->SetBranchAddress("delta_x",delta_x);
   pik->SetBranchAddress("delta_seg",delta_seg);
   pik->SetBranchAddress("nhSftX",&nhSftX);
   pik->SetBranchAddress("SftXSeg",SftXSeg);
   pik->SetBranchAddress("nlBcOut",&nlBcOut);
   pik->SetBranchAddress("ntBcOut",&ntBcOut);
   pik->SetBranchAddress("nhBcOut",nhBcOut);
   pik->SetBranchAddress("chisqrBcOut",chisqrBcOut);
   pik->SetBranchAddress("x0BcOut",x0BcOut);
   pik->SetBranchAddress("y0BcOut",y0BcOut);
   pik->SetBranchAddress("u0BcOut",u0BcOut);
   pik->SetBranchAddress("v0BcOut",v0BcOut);
   pik->SetBranchAddress("xtgtBcOut",xtgtBcOut);
   pik->SetBranchAddress("ytgtBcOut",ytgtBcOut);
   pik->SetBranchAddress("xbh2BcOut",xbh2BcOut);
   pik->SetBranchAddress("ybh2BcOut",ybh2BcOut);
   pik->SetBranchAddress("ntK18",&ntK18);
   pik->SetBranchAddress("nhK18",nhK18);
   pik->SetBranchAddress("chisqrK18",chisqrK18);
   pik->SetBranchAddress("pK18",pK18);
   pik->SetBranchAddress("xtgtK18",xtgtK18);
   pik->SetBranchAddress("ytgtK18",ytgtK18);
   pik->SetBranchAddress("utgtK18",utgtK18);
   pik->SetBranchAddress("vtgtK18",vtgtK18);
   pik->SetBranchAddress("thetaK18",thetaK18);
   pik->SetBranchAddress("nlSdcIn",&nlSdcIn);
   pik->SetBranchAddress("ntSdcIn",&ntSdcIn);
   pik->SetBranchAddress("nhSdcIn",nhSdcIn);
   pik->SetBranchAddress("chisqrSdcIn",chisqrSdcIn);
   pik->SetBranchAddress("x0SdcIn",x0SdcIn);
   pik->SetBranchAddress("y0SdcIn",y0SdcIn);
   pik->SetBranchAddress("u0SdcIn",u0SdcIn);
   pik->SetBranchAddress("v0SdcIn",v0SdcIn);
   pik->SetBranchAddress("nlSdcOut",&nlSdcOut);
   pik->SetBranchAddress("ntSdcOut",&ntSdcOut);
   pik->SetBranchAddress("nhSdcOut",nhSdcOut);
   pik->SetBranchAddress("chisqrSdcOut",chisqrSdcOut);
   pik->SetBranchAddress("x0SdcOut",x0SdcOut);
   pik->SetBranchAddress("y0SdcOut",y0SdcOut);
   pik->SetBranchAddress("u0SdcOut",u0SdcOut);
   pik->SetBranchAddress("v0SdcOut",v0SdcOut);
   pik->SetBranchAddress("ntKurama",&ntKurama);
   pik->SetBranchAddress("nhKurama",nhKurama);
   pik->SetBranchAddress("chisqrKurama",chisqrKurama);
   pik->SetBranchAddress("stof",stof);
   pik->SetBranchAddress("path",path);
   pik->SetBranchAddress("pKurama",pKurama);
   pik->SetBranchAddress("qKurama",qKurama);
   pik->SetBranchAddress("m2",m2);
   pik->SetBranchAddress("xtgtKurama",xtgtKurama);
   pik->SetBranchAddress("ytgtKurama",ytgtKurama);
   pik->SetBranchAddress("utgtKurama",utgtKurama);
   pik->SetBranchAddress("vtgtKurama",vtgtKurama);
   pik->SetBranchAddress("thetaKurama",thetaKurama);
   pik->SetBranchAddress("xtofKurama",xtofKurama);
   pik->SetBranchAddress("ytofKurama",ytofKurama);
   pik->SetBranchAddress("utofKurama",utofKurama);
   pik->SetBranchAddress("vtofKurama",vtofKurama);
   pik->SetBranchAddress("tofsegKurama",tofsegKurama);
   pik->SetBranchAddress("sftxsegKurama",&sftxsegKurama);
   pik->SetBranchAddress("vpx",vpx);
   pik->SetBranchAddress("vpy",vpy);
   pik->SetBranchAddress("vpseg",vpseg);
   pik->SetBranchAddress("nPi",&nPi);
   pik->SetBranchAddress("nK",&nK);
   pik->SetBranchAddress("nPiK",&nPiK);
   pik->SetBranchAddress("vtx",vtx);
   pik->SetBranchAddress("vty",vty);
   pik->SetBranchAddress("vtz",vtz);
   pik->SetBranchAddress("closeDist",closeDist);
   pik->SetBranchAddress("theta",theta);
   pik->SetBranchAddress("MissMass",MissMass);
   pik->SetBranchAddress("MissMassCorr",MissMassCorr);
   pik->SetBranchAddress("MissMassCorrDE",MissMassCorrDE);
   pik->SetBranchAddress("thetaCM",thetaCM);
   pik->SetBranchAddress("costCM",costCM);
   pik->SetBranchAddress("xpi",xpi);
   pik->SetBranchAddress("ypi",ypi);
   pik->SetBranchAddress("upi",upi);
   pik->SetBranchAddress("vpi",vpi);
   pik->SetBranchAddress("xk",xk);
   pik->SetBranchAddress("yk",yk);
   pik->SetBranchAddress("uk",uk);
   pik->SetBranchAddress("vk",vk);
   pik->SetBranchAddress("pOrg",pOrg);
   pik->SetBranchAddress("pCalc",pCalc);
   pik->SetBranchAddress("pCorr",pCorr);
   pik->SetBranchAddress("pCorrDE",pCorrDE);

//     This is the loop skeleton
//       To read only selected branches, Insert statements like:
// pik->SetBranchStatus("*",0);  // disable all branches
// TTreePlayer->SetBranchStatus("branchname",1);  // activate branchname

   Long64_t nentries = pik->GetEntries();

   Long64_t nbytes = 0;
//   for (Long64_t i=0; i<nentries;i++) {
//      nbytes += pik->GetEntry(i);
//   }
}
