{
//////////////////////////////////////////////////////////
//   This file has been automatically generated 
//     (Fri Dec 21 01:38:49 2018 by ROOT version6.10/08)
//   from TTree kurama/tree of KuramaTracking
//   found on file: rootfile/run05078_KuramaTracking.root
//////////////////////////////////////////////////////////


//Reset ROOT and connect tree file
   gROOT->Reset();
   TFile *f = (TFile*)gROOT->GetListOfFiles()->FindObject("rootfile/run05078_KuramaTracking.root");
   if (!f) {
      f = new TFile("rootfile/run05078_KuramaTracking.root");
   }
    f->GetObject("kurama",tree);

//Declaration of leaves types
   Int_t           evnum;
   Int_t           trigpat[32];
   Int_t           trigflag[32];
   Int_t           nhBh2;
   Double_t        Bh2Seg[8];
   Double_t        tBh2[8];
   Double_t        deBh2[8];
   Double_t        time0;
   Int_t           nhBh1;
   Double_t        Bh1Seg[11];
   Double_t        tBh1[11];
   Double_t        deBh1[11];
   Double_t        btof;
   Int_t           nhSac;
   Double_t        SacSeg[4];
   Double_t        tSac[4];
   Double_t        deSac[4];
   Int_t           nhTof;
   Double_t        TofSeg[12];
   Double_t        tTof[12];
   Double_t        dtTof[12];
   Double_t        deTof[12];
   Double_t        wposSdcIn[9];
   Double_t        wposSdcOut[16];
   Int_t           ntSdcIn;
   Int_t           much;
   Int_t           nlSdcIn;
   Int_t           nhSdcIn[8];
   Double_t        chisqrSdcIn[8];
   Double_t        x0SdcIn[8];
   Double_t        y0SdcIn[8];
   Double_t        u0SdcIn[8];
   Double_t        v0SdcIn[8];
   Int_t           ntSdcOut;
   Int_t           nlSdcOut;
   Int_t           nhSdcOut[3];
   Double_t        chisqrSdcOut[3];
   Double_t        x0SdcOut[3];
   Double_t        y0SdcOut[3];
   Double_t        u0SdcOut[3];
   Double_t        v0SdcOut[3];
   Int_t           ntKurama;
   Int_t           nlKurama;
   Int_t           nhKurama[4];
   Double_t        chisqrKurama[4];
   Double_t        stof[4];
   Double_t        path[4];
   Double_t        pKurama[4];
   Double_t        qKurama[4];
   Double_t        m2[4];
   Double_t        xtgtKurama[4];
   Double_t        ytgtKurama[4];
   Double_t        utgtKurama[4];
   Double_t        vtgtKurama[4];
   Double_t        thetaKurama[4];
   Double_t        phiKurama[4];
   Double_t        resP[4];
   Double_t        xsacKurama[4];
   Double_t        ysacKurama[4];
   Double_t        xtofKurama[4];
   Double_t        ytofKurama[4];
   Double_t        utofKurama[4];
   Double_t        vtofKurama[4];
   Double_t        tofsegKurama[4];
   Double_t        vpx[5];
   Double_t        vpy[5];
   vector<double>  ResL1;
   vector<double>  ResL2;
   vector<double>  ResL3;
   vector<double>  ResL4;
   vector<double>  ResL5;
   vector<double>  ResL6;
   vector<double>  ResL7;
   vector<double>  ResL8;
   vector<double>  ResL9;
   vector<double>  ResL31;
   vector<double>  ResL32;
   vector<double>  ResL33;
   vector<double>  ResL34;
   vector<double>  ResL35;
   vector<double>  ResL36;
   vector<double>  ResL37;
   vector<double>  ResL38;
   vector<double>  ResL39;
   vector<double>  ResL40;
   vector<double>  ResL41;
   vector<double>  ResL42;
   vector<double>  ResL43;
   vector<double>  ResL44;
   vector<double>  ResL45;
   vector<double>  ResL46;
   vector<double>  ResL41;
   vector<double>  ResL42;
   vector<double>  ResG1;
   vector<double>  ResG2;
   vector<double>  ResG3;
   vector<double>  ResG4;
   vector<double>  ResG5;
   vector<double>  ResG6;
   vector<double>  ResG7;
   vector<double>  ResG8;
   vector<double>  ResG9;
   vector<double>  ResG31;
   vector<double>  ResG32;
   vector<double>  ResG33;
   vector<double>  ResG34;
   vector<double>  ResG35;
   vector<double>  ResG36;
   vector<double>  ResG37;
   vector<double>  ResG38;
   vector<double>  ResG39;
   vector<double>  ResG40;
   vector<double>  ResG41;
   vector<double>  ResG42;
   vector<double>  ResG43;
   vector<double>  ResG44;
   vector<double>  ResG45;
   vector<double>  ResG46;
   vector<double>  ResG41;
   vector<double>  ResG42;
   Double_t        tTofCalc[3];
   Double_t        utTofSeg[24];
   Double_t        dtTofSeg[24];
   Double_t        udeTofSeg[24];
   Double_t        ddeTofSeg[24];
   Double_t        tofua[24];
   Double_t        tofda[24];

   // Set branch addresses.
   kurama->SetBranchAddress("evnum",&evnum);
   kurama->SetBranchAddress("trigpat",trigpat);
   kurama->SetBranchAddress("trigflag",trigflag);
   kurama->SetBranchAddress("nhBh2",&nhBh2);
   kurama->SetBranchAddress("Bh2Seg",Bh2Seg);
   kurama->SetBranchAddress("tBh2",tBh2);
   kurama->SetBranchAddress("deBh2",deBh2);
   kurama->SetBranchAddress("time0",&time0);
   kurama->SetBranchAddress("nhBh1",&nhBh1);
   kurama->SetBranchAddress("Bh1Seg",Bh1Seg);
   kurama->SetBranchAddress("tBh1",tBh1);
   kurama->SetBranchAddress("deBh1",deBh1);
   kurama->SetBranchAddress("btof",&btof);
   kurama->SetBranchAddress("nhSac",&nhSac);
   kurama->SetBranchAddress("SacSeg",SacSeg);
   kurama->SetBranchAddress("tSac",tSac);
   kurama->SetBranchAddress("deSac",deSac);
   kurama->SetBranchAddress("nhTof",&nhTof);
   kurama->SetBranchAddress("TofSeg",TofSeg);
   kurama->SetBranchAddress("tTof",tTof);
   kurama->SetBranchAddress("dtTof",dtTof);
   kurama->SetBranchAddress("deTof",deTof);
   kurama->SetBranchAddress("wposSdcIn",wposSdcIn);
   kurama->SetBranchAddress("wposSdcOut",wposSdcOut);
   kurama->SetBranchAddress("ntSdcIn",&ntSdcIn);
   kurama->SetBranchAddress("much",&much);
   kurama->SetBranchAddress("nlSdcIn",&nlSdcIn);
   kurama->SetBranchAddress("nhSdcIn",nhSdcIn);
   kurama->SetBranchAddress("chisqrSdcIn",chisqrSdcIn);
   kurama->SetBranchAddress("x0SdcIn",x0SdcIn);
   kurama->SetBranchAddress("y0SdcIn",y0SdcIn);
   kurama->SetBranchAddress("u0SdcIn",u0SdcIn);
   kurama->SetBranchAddress("v0SdcIn",v0SdcIn);
   kurama->SetBranchAddress("ntSdcOut",&ntSdcOut);
   kurama->SetBranchAddress("nlSdcOut",&nlSdcOut);
   kurama->SetBranchAddress("nhSdcOut",nhSdcOut);
   kurama->SetBranchAddress("chisqrSdcOut",chisqrSdcOut);
   kurama->SetBranchAddress("x0SdcOut",x0SdcOut);
   kurama->SetBranchAddress("y0SdcOut",y0SdcOut);
   kurama->SetBranchAddress("u0SdcOut",u0SdcOut);
   kurama->SetBranchAddress("v0SdcOut",v0SdcOut);
   kurama->SetBranchAddress("ntKurama",&ntKurama);
   kurama->SetBranchAddress("nlKurama",&nlKurama);
   kurama->SetBranchAddress("nhKurama",nhKurama);
   kurama->SetBranchAddress("chisqrKurama",chisqrKurama);
   kurama->SetBranchAddress("stof",stof);
   kurama->SetBranchAddress("path",path);
   kurama->SetBranchAddress("pKurama",pKurama);
   kurama->SetBranchAddress("qKurama",qKurama);
   kurama->SetBranchAddress("m2",m2);
   kurama->SetBranchAddress("xtgtKurama",xtgtKurama);
   kurama->SetBranchAddress("ytgtKurama",ytgtKurama);
   kurama->SetBranchAddress("utgtKurama",utgtKurama);
   kurama->SetBranchAddress("vtgtKurama",vtgtKurama);
   kurama->SetBranchAddress("thetaKurama",thetaKurama);
   kurama->SetBranchAddress("phiKurama",phiKurama);
   kurama->SetBranchAddress("resP",resP);
   kurama->SetBranchAddress("xsacKurama",xsacKurama);
   kurama->SetBranchAddress("ysacKurama",ysacKurama);
   kurama->SetBranchAddress("xtofKurama",xtofKurama);
   kurama->SetBranchAddress("ytofKurama",ytofKurama);
   kurama->SetBranchAddress("utofKurama",utofKurama);
   kurama->SetBranchAddress("vtofKurama",vtofKurama);
   kurama->SetBranchAddress("tofsegKurama",tofsegKurama);
   kurama->SetBranchAddress("vpx",vpx);
   kurama->SetBranchAddress("vpy",vpy);
   kurama->SetBranchAddress("ResL1",&ResL1);
   kurama->SetBranchAddress("ResL2",&ResL2);
   kurama->SetBranchAddress("ResL3",&ResL3);
   kurama->SetBranchAddress("ResL4",&ResL4);
   kurama->SetBranchAddress("ResL5",&ResL5);
   kurama->SetBranchAddress("ResL6",&ResL6);
   kurama->SetBranchAddress("ResL7",&ResL7);
   kurama->SetBranchAddress("ResL8",&ResL8);
   kurama->SetBranchAddress("ResL9",&ResL9);
   kurama->SetBranchAddress("ResL31",&ResL31);
   kurama->SetBranchAddress("ResL32",&ResL32);
   kurama->SetBranchAddress("ResL33",&ResL33);
   kurama->SetBranchAddress("ResL34",&ResL34);
   kurama->SetBranchAddress("ResL35",&ResL35);
   kurama->SetBranchAddress("ResL36",&ResL36);
   kurama->SetBranchAddress("ResL37",&ResL37);
   kurama->SetBranchAddress("ResL38",&ResL38);
   kurama->SetBranchAddress("ResL39",&ResL39);
   kurama->SetBranchAddress("ResL40",&ResL40);
   kurama->SetBranchAddress("ResL41",&ResL41);
   kurama->SetBranchAddress("ResL42",&ResL42);
   kurama->SetBranchAddress("ResL43",&ResL43);
   kurama->SetBranchAddress("ResL44",&ResL44);
   kurama->SetBranchAddress("ResL45",&ResL45);
   kurama->SetBranchAddress("ResL46",&ResL46);
   kurama->SetBranchAddress("ResL41",&ResL41);
   kurama->SetBranchAddress("ResL42",&ResL42);
   kurama->SetBranchAddress("ResG1",&ResG1);
   kurama->SetBranchAddress("ResG2",&ResG2);
   kurama->SetBranchAddress("ResG3",&ResG3);
   kurama->SetBranchAddress("ResG4",&ResG4);
   kurama->SetBranchAddress("ResG5",&ResG5);
   kurama->SetBranchAddress("ResG6",&ResG6);
   kurama->SetBranchAddress("ResG7",&ResG7);
   kurama->SetBranchAddress("ResG8",&ResG8);
   kurama->SetBranchAddress("ResG9",&ResG9);
   kurama->SetBranchAddress("ResG31",&ResG31);
   kurama->SetBranchAddress("ResG32",&ResG32);
   kurama->SetBranchAddress("ResG33",&ResG33);
   kurama->SetBranchAddress("ResG34",&ResG34);
   kurama->SetBranchAddress("ResG35",&ResG35);
   kurama->SetBranchAddress("ResG36",&ResG36);
   kurama->SetBranchAddress("ResG37",&ResG37);
   kurama->SetBranchAddress("ResG38",&ResG38);
   kurama->SetBranchAddress("ResG39",&ResG39);
   kurama->SetBranchAddress("ResG40",&ResG40);
   kurama->SetBranchAddress("ResG41",&ResG41);
   kurama->SetBranchAddress("ResG42",&ResG42);
   kurama->SetBranchAddress("ResG43",&ResG43);
   kurama->SetBranchAddress("ResG44",&ResG44);
   kurama->SetBranchAddress("ResG45",&ResG45);
   kurama->SetBranchAddress("ResG46",&ResG46);
   kurama->SetBranchAddress("ResG41",&ResG41);
   kurama->SetBranchAddress("ResG42",&ResG42);
   kurama->SetBranchAddress("tTofCalc",tTofCalc);
   kurama->SetBranchAddress("utTofSeg",utTofSeg);
   kurama->SetBranchAddress("dtTofSeg",dtTofSeg);
   kurama->SetBranchAddress("udeTofSeg",udeTofSeg);
   kurama->SetBranchAddress("ddeTofSeg",ddeTofSeg);
   kurama->SetBranchAddress("tofua",tofua);
   kurama->SetBranchAddress("tofda",tofda);

//     This is the loop skeleton
//       To read only selected branches, Insert statements like:
// kurama->SetBranchStatus("*",0);  // disable all branches
// TTreePlayer->SetBranchStatus("branchname",1);  // activate branchname

   Long64_t nentries = kurama->GetEntries();

   Long64_t nbytes = 0;
//   for (Long64_t i=0; i<nentries;i++) {
//      nbytes += kurama->GetEntry(i);
//   }
}
